const pathImages = "./src/assets/icons/";

const cartas = [
  {
    id: 0,
    nome: "Dragão Branco de Olhos azuis",
    tipo: "Lagarto",
    img: `${pathImages}dragon.png`,
    poder: 900,
    efeito: "Nenhum",
  },
  {
    id: 1,
    name: "Mago Negro",
    type: "Spock",
    img: `${pathImages}magician.png`,
    poder: 800,
    efeito: "Nenhum",
  },
  {
    id: 2,
    name: "Exodia",
    type: "Pedra",
    img: `${pathImages}exodia.png`,
    poder: 400,
    efeito: "Aumenta o poder a cada turno em campo",
  },
  {
    id: 3,
    name: "Rei Caveira",
    type: "Papel",
    img: `${pathImages}exodia.png`,
    poder: 650,
    efeito: "Nenhum",
  },
  {
    id: 4,
    name: "Guardião Celta",
    type: "Tesoura",
    img: `${pathImages}exodia.png`,
    poder: 600,
    efeito: "Nenhum",
  },
  {
    id: 5,
    nome: "Dragão Branco de Olhos azuis",
    tipo: "Lagarto",
    img: `${pathImages}dragon.png`,
    poder: 900,
    efeito: "Nenhum",
  },
  {
    id: 6,
    name: "Mago Negro",
    type: "Spock",
    img: `${pathImages}magician.png`,
    poder: 800,
    efeito: "Nenhum",
  },
  {
    id: 7,
    name: "Exodia",
    type: "Pedra",
    img: `${pathImages}exodia.png`,
    poder: 400,
    efeito: "Aumenta o poder a cada turno em campo",
  },
  {
    id: 8,
    name: "Rei Caveira",
    type: "Papel",
    img: `${pathImages}exodia.png`,
    poder: 650,
    efeito: "Nenhum",
  },
  {
    id: 9,
    name: "Guardião Celta",
    type: "Tesoura",
    img: `${pathImages}exodia.png`,
    poder: 600,
    efeito: "Nenhum",
  },
  {
    id: 10,
    nome: "Dragão Branco de Olhos azuis",
    tipo: "Lagarto",
    img: `${pathImages}dragon.png`,
    poder: 900,
    efeito: "Nenhum",
  },
  {
    id: 11,
    name: "Mago Negro",
    type: "Spock",
    img: `${pathImages}magician.png`,
    poder: 800,
    efeito: "Nenhum",
  },
  {
    id: 12,
    name: "Exodia",
    type: "Pedra",
    img: `${pathImages}exodia.png`,
    poder: 400,
    efeito: "Aumenta o poder a cada turno em campo",
  },
  {
    id: 13,
    name: "Rei Caveira",
    type: "Papel",
    img: `${pathImages}exodia.png`,
    poder: 650,
    efeito: "Nenhum",
  },
  {
    id: 14,
    name: "Guardião Celta",
    type: "Tesoura",
    img: `${pathImages}exodia.png`,
    poder: 600,
    efeito: "Nenhum",
  },
];

const yugi = {
  cartas: cartas,
};

const estado = {
  telas: {
    telaInicial: document.getElementById("tela-inicial"),
    telaJogo: document.getElementById("tela-jogo"),
  },
  cartaoExibido: {
    imagem: document.getElementById("carta-imagem"),
    nome: document.getElementById("carta-nome"),
    tipo: document.getElementById("carta-tipo"),
    efeito: document.getElementById("carta-poder"),
    efeito: document.getElementById("carta-efeito"),
  },
  cartasEmCampo: {
    carta1: document.getElementById("carta-jogador-1"),
    carta2: document.getElementById("carta-jogador-2"),
    carta3: document.getElementById("carta-jogador-3"),
    carta4: document.getElementById("carta-jogador-4"),
    carta5: document.getElementById("carta-jogador-5"),
  },
  jogador: {
    personagem: yugi,
    energia: 2000,
    efeitos: [],
  },
  computador: {
    personagem: yugi,
    energia: 2000,
    efeitos: [],
  },
  batalha: {
    turno: 1,
    posicaoDeck: 0,
    iniciado: false,
  },
};
